[config]

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/themes/colors.conf"
post_hook = "kitty +kitten themes --reload-in=all colors"

[templates.clock-rs]
input_path = "~/.config/matugen/templates/clock-rs-conf.toml"
output_path = "~/.config/clock-rs/conf.toml"


[templates.space-bar]
input_path = "~/.config/matugen/templates/space-bar.css"
output_path = "~/.config/colors/space-bar.css"

[templates.search-light]
input_path = "~/.config/matugen/templates/search-light.css"
output_path = "~/.config/colors/search-light.css"

[templates.pop-shell]
input_path = "~/.config/matugen/templates/pop-shell.css"
output_path = "~/.config/colors/pop-shell.css"

[templates.fix]
input_path = "~/.config/matugen/templates/fix.css"
output_path = "~/.config/colors/fix.css"

# [templates.sherlock]
# input_path = "~/.config/matugen/templates/sherlock.css"
# output_path = "~/.config/sherlock/main.css"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.lockscreen]
input_path = "~/.config/matugen/templates/accent-color.css"
output_path = "~/.config/colors/accent-color.css"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3-colors.css'
output_path = '~/.themes/Material-Gnome/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4-colors.css'
output_path = '~/.themes/Material-Gnome/gtk-4.0/colors.css'

[templates.gtk3_theme]
input_path = '~/.config/matugen/templates/gtk3-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4_theme]
input_path = '~/.config/matugen/templates/gtk4-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.micro]
input_path = '~/.config/matugen/templates/micro-colors.micro'
output_path = '~/.config/micro/colorschemes/colors.micro'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/colors.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/colors.conf'

[templates.mpv]
input_path = '~/.config/matugen/templates/mpv-uosc.conf'
output_path = '~/.config/mpv/script-opts/uosc.conf'

[templates.mpv-config]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.config/colors.json'

[templates.colors]
input_path = '~/.config/matugen/templates/mpv-config.conf'
output_path = '~/.config/mpv/mpv.conf'

[templates.gnome-shell]
input_path = '~/.config/matugen/templates/gnome-shell.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/gnome-shell.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = "pkill -USR2 btop"

[templates.kew]
input_path = '~/.config/matugen/templates/kew.theme'
output_path = '~/.config/kew/themes/matugen.theme'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/cava'
post_hook = "pkill -USR1 cava"

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.spf]
input_path = '~/.config/matugen/templates/superfile.toml'
output_path = '~/.config/superfile/theme/matugen.toml'

[templates.zen]
input_path = '~/.config/matugen/templates/zen_colors.css'
output_path = '~/.zen/b4z0ycdk.Default (release)/chrome/colors.css'

[templates.zen-accent]
input_path = '~/.config/matugen/templates/zen-accent.js'
output_path = '~/.zen/b4z0ycdk.Default (release)/user.js'

#[templates.userContent]
#input_path = '~/.config/matugen/templates/userContent.css'
#output_path = '~/.zen/b4z0ycdk.Default (release)/chrome/content.css'
