[config]

caching = true

# choices:
# [darkness, lightness, saturation, less-saturation, value, closest-to-fallback]
# prefer = ""

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = "pkill -USR2 btop || true"

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/cava'
post_hook = "pkill -USR1 cava"

[templates.clock-rs]
input_path = "~/.config/matugen/templates/clock-rs-conf.toml"
output_path = "~/.config/clock-rs/conf.toml"
post_hook = "pkill -USR1 clock-rs"

[templates.colors]
input_path = '~/.config/matugen/templates/mpv-config.conf'
output_path = '~/.config/mpv/mpv.conf'

[templates.fish]
input_path = '~/.config/matugen/templates/fish.tpl'
output_path = '~/.config/fish/matugen_colors.fish'
post_hook = "fish -c 'set -U MATUGEN_RELOAD_TRIGGER (date +%s)'"

[templates.fix]
input_path = "~/.config/matugen/templates/fix.css"
output_path = "~/.config/colors/fix.css"

[templates.gnome-shell]
input_path = '~/.config/matugen/templates/gnome-shell.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/gnome-shell-stub.css'
# post_hook = "~/.config/matugen/post-hook-scripts/merge-layout.sh"

[templates.gnome-shell-active]
input_path = "~/.config/matugen/templates/gnome-active-layout.css"
output_path = "~/.themes/Material-Gnome/gnome-shell/layouts/active-layout.css"

[templates.gnome-shell-floating-capsule]
input_path = '~/.config/matugen/templates/gnome-floating-capsule.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/floating-capsule.css'

[templates.gnome-shell-floating-capsule-glass]
input_path = '~/.config/matugen/templates/gnome-floating-capsule-glass.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/floating-capsule-glass.css'

[templates.gnome-shell-pill-duo]
input_path = '~/.config/matugen/templates/gnome-pill-duo.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/pill-duo.css'

[templates.gnome-unified-pill]
input_path = '~/.config/matugen/templates/gnome-segmented-pill.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/segmented-pill.css'

[templates.gnome-unified-bar]
input_path = '~/.config/matugen/templates/gnome-unified-bar.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/unified-bar.css'

[templates.gnome-unified-capsule]
input_path = '~/.config/matugen/templates/gnome-unified-capsule.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/unified-capsule.css'

[templates.gnome-structured-box]
input_path = '~/.config/matugen/templates/gnome-structured-box.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/structured-box.css'

[templates.gnome-default]
input_path = '~/.config/matugen/templates/gnome-default.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/default.css'

[templates.gnome-unified-border]
input_path = '~/.config/matugen/templates/gnome-unified-border.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/unified-border.css'

[templates.gnome-segmented-dock]
input_path = '~/.config/matugen/templates/gnome-segmented-dock.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/segmented-dock.css'

[templates.gnome-default-transperacy]
input_path = '~/.config/matugen/templates/gnome-default-transparecy.css'
output_path = '~/.themes/Material-Gnome/gnome-shell/layouts/default-transparecy.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3-colors.css'
output_path = '~/.themes/Material-Gnome/gtk-3.0/colors.css'

[templates.gtk3_theme]
input_path = '~/.config/matugen/templates/gtk3-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme "Material-Gnome"'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4-colors.css'
output_path = '~/.themes/Material-Gnome/gtk-4.0/colors.css'

[templates.gtk4_theme]
input_path = '~/.config/matugen/templates/gtk4-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.kew]
input_path = '~/.config/matugen/templates/kew.theme'
output_path = '~/.config/kew/themes/matugen.theme'

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.kvantum_kvconfig]
input_path = './templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = './templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.lockscreen]
input_path = '~/.config/matugen/templates/clock-color.css'
output_path = '~/.config/colors/clock-color.css'

[templates.micro]
input_path = '~/.config/matugen/templates/micro-colors.micro'
output_path = '~/.config/micro/colorschemes/colors.micro'

[templates.mpv]
input_path = '~/.config/matugen/templates/mpv-uosc.conf'
output_path = '~/.config/mpv/script-opts/uosc.conf'

[templates.mpv-config]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.config/colors.json'

[templates.pop-shell]
input_path = "~/.config/matugen/templates/pop-shell.css"
output_path = "~/.config/colors/pop-shell.css"

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/colors.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/colors.conf'

[templates.search-light]
input_path = "~/.config/matugen/templates/search-light.css"
output_path = "~/.config/colors/search-light.css"

# [templates.sherlock]
# input_path = "~/.config/matugen/templates/sherlock.css"
# output_path = "~/.config/sherlock/main.css"

[templates.space-bar]
input_path = "~/.config/matugen/templates/space-bar.css"
output_path = "~/.config/colors/space-bar.css"

#[templates.spf]
#input_path = '~/.config/matugen/templates/superfile.toml'
#output_path = '~/.config/superfile/theme/matugen.toml'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.zen]
input_path = '~/.config/matugen/templates/zen_colors.css'
output_path = '~/.zen/oup922t1.Default (release)/chrome/colors1.css'

[templates.zen-about-pages-colors]
input_path = "~/.config/matugen/templates/zen-about-pages.css"
output_path = "~/.zen/oup922t1.Default (release)/chrome/zen-about-pages.css"

[templates.zen-accent]
input_path = '~/.config/matugen/templates/zen-accent.js'
output_path = '~/.zen/oup922t1.Default (release)/user.js'

[templates.zen-browser-website-colors]
input_path = "~/.config/matugen/templates/zen-colors.css"
output_path = "~/.zen/oup922t1.Default (release)/chrome/colors.css"
