# Matugen template for btop

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#D5C4A1"

# Title color for boxes
theme[title]="#7DAEA3"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#6C827D"

# Background color of selected item in processes box
theme[selected_bg]="#7DAEA3"

# Foreground color of selected item in processes box
theme[selected_fg]="#F2E5BC"

# Color of inactive/disabled text
theme[inactive_fg]="#A89984"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#5C8C84"

# Cpu box outline color
theme[cpu_box]="#928374"

# Memory/disks box outline color
theme[mem_box]="#928374"

# Net up/down box outline color
theme[net_box]="#928374"

# Processes box outline color
theme[proc_box]="#928374"

# Box divider line and small boxes line color
theme[div_line]="#665C54"

# Temperature graph colors
theme[temp_start]="#6C827D"
theme[temp_mid]="#7DAEA3"
theme[temp_end]="#FB4934"

# CPU graph colors
theme[cpu_start]="#6C827D"
theme[cpu_mid]="#7DAEA3"
theme[cpu_end]="#FB4934"

# Mem/Disk free meter
theme[free_start]="#6C827D"
theme[free_mid]=""
theme[free_end]="#2E4F4B"

# Mem/Disk cached meter
theme[cached_start]="#5C8C84"
theme[cached_mid]=""
theme[cached_end]="#334F4B"

# Mem/Disk available meter
theme[available_start]="#7DAEA3"
theme[available_mid]=""
theme[available_end]="#33504C"

# Mem/Disk used meter
theme[used_start]="#FB4934"
theme[used_mid]=""
theme[used_end]="#3C1E1E"

# Download graph colors
theme[download_start]="#6C827D"
theme[download_mid]="#7DAEA3"
theme[download_end]="#5C8C84"

# Upload graph colors
theme[upload_start]="#6C827D"
theme[upload_mid]="#7DAEA3"
theme[upload_end]="#5C8C84"

