cursor #D5C4A1
cursor_text_color #A89984

foreground            #D5C4A1
background            #1D2021
selection_foreground  #6C827D
selection_background  #131313
url_color             #7DAEA3

# black
color8   #262626
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green
color2   #8aac8b
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #7DAEA3
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #7DAEA3

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0

