palette = 0="#fbf1c7"
palette = 1="rgba(251, 241, 199, 0.5)"
palette = 2="#fbf1c7"
palette = 3="{{colors.secondary_variant.default.hex}}"
palette = 4="#7daea3"
palette = 5="{{colors.primary_variant.default.hex}}"
palette = 6="#b47109"
palette = 7="{{colors.tertiary_variant.default.hex}}"
palette = 8="#1d2021"
palette = 9="#282524"
palette = 10="rgba(29, 32, 33, 0.87)"
palette = 11="rgba(29, 32, 33, 0.87)"
palette = 12="rgba(29, 32, 33, 0.87)"
palette = 13="#fbf1c7"
palette = 14="rgba(251, 241, 199, 0.5)"
palette = 15="{{colors.primary_variant.default.hex}}"

background = "#1d2021"
foreground = "#fbf1c7"
cursor-color = "rgba(251, 241, 199, 0.5)"
cursor-text = "#fbf1c7"
selection-background = "#fbf1c7"
selection-foreground = "rgba(29, 32, 33, 0.87)"
url_color = "#7daea3"
