# : Manager [[[

[manager]
cwd = { fg = "#E2E2E2" }  # on_background

# Tab
tab_active = { fg = "#FFFFFF", bg = "#7DAEA3", bold = true }  # on_primary / primary
tab_inactive = { fg = "#2E004D", bg = "#B5A1D3" }  # primary_fixed / on_primary_fixed
tab_width = 1

# Find
find_keyword = { fg = "#FB4934", bold = true, italic = true, underline = true }  # error
find_position = { fg = "#FB4934", bold = true }

# Marker
marker_copied = { fg = "#94D2D2", bg = "#94D2D2" }  # tertiary_fixed auto_lightness
marker_cut = { fg = "#7DAEA3", bg = "#7DAEA3" }  # tertiary_fixed
marker_marked = { fg = "#FB4934", bg = "#FB4934" }  # error
marker_selected = { fg = "#7DAEA3", bg = "#7DAEA3" }  # tertiary

# Count
count_copied = { fg = "#E2E2E2", bg = "#94D2D2" }  # on_tertiary_fixed / tertiary_fixed
count_cut = { fg = "#E2E2E2", bg = "#94D2D2" }
count_selected = { fg = "#FFFFFF", bg = "#7DAEA3" }  # on_primary / tertiary

# Border
border_symbol = "│"
border_style  = { fg = "#C8FFF4" }  # surface_tint

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#FFFFFF", fg = "#F4A261" }  # on_primary / highlight

[mode]
normal_main = { bg = "#7DAEA3", fg = "#FFFFFF", bold = true }  # primary / on_primary
normal_alt  = { bg = "#C8FFF4", fg = "#E2E2E2" }  # surface_variant / on_surface_variant

select_main = { bg = "#94D2D2", fg = "#E2E2E2", bold = true }  # secondary / on_secondary
select_alt  = { bg = "#C8FFF4", fg = "#E2E2E2" }

unset_main = { bg = "#7DAEA3", fg = "#FFFFFF", bold = true }  # tertiary / on_tertiary
unset_alt  = { bg = "#C8FFF4", fg = "#E2E2E2" }

progress_label = { bold = true }
progress_normal = { fg = "#7DAEA3", bg = "#D9FFFF" }  # primary / surface_bright
progress_error = { fg = "#FB4934", bg = "#D9FFFF" }

permissions_t = { fg = "#A3DAD2" }
permissions_w = { fg = "#7DAEA3" }
permissions_x = { fg = "#FB4934" }
permissions_r = { fg = "#94D2D2" }
permissions_s = { fg = "#B5A1D3" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#7DAEA3" }
active = { fg = "#7DAEA3", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#7DAEA3" }
value = { fg = "#E2E2E2" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#7DAEA3", bg = "#FFFFFF" }  # primary / on_primary

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7DAEA3" }
title = {}
hovered = { fg = "#94D2D2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#D9FFFF" }
cand = { fg = "#7DAEA3" }
rest = { fg = "#FFFFFF" }
desc = { fg = "#E2E2E2" }
separator = " ▶ "
separator_style = { fg = "#E2E2E2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#E2E2E2" }
run = { fg = "#E2E2E2" }
footer = { fg = "#94D2D2", bg = "#7DAEA3" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#7DAEA3" }
title_warn = { fg = "#7DAEA3" }
title_error = { fg = "#FB4934" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#FB4934" },
    { name = "*", is = "exec", fg = "#FFFFFF" },

    # Fallback
    { name = "*", fg = "#E2E2E2" },
    { name = "*/", fg = "#C8FFF4" },
]

# : ]]]

