palette = 0="{{colors.on_surface.default.hex}}"
palette = 1="{{colors.on_surface_variant.default.hex}}"
palette = 2="{{colors.secondary.default.hex}}"
palette = 3="{{colors.secondary_variant.default.hex}}"
palette = 4="{{colors.primary.default.hex}}"
palette = 5="{{colors.primary_variant.default.hex}}"
palette = 6="{{colors.tertiary.default.hex}}"
palette = 7="{{colors.tertiary_variant.default.hex}}"
palette = 8="{{colors.surface.default.hex}}"
palette = 9="{{colors.surface_variant.default.hex}}"
palette = 10="{{colors.on_primary.default.hex}}"
palette = 11="{{colors.on_secondary.default.hex}}"
palette = 12="{{colors.on_tertiary.default.hex}}"
palette = 13="{{colors.on_surface.default.hex}}"
palette = 14="{{colors.on_surface_variant.default.hex}}"
palette = 15="{{colors.primary_variant.default.hex}}"

background = "{{colors.surface.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"
cursor-color = "{{colors.on_surface_variant.default.hex}}"
cursor-text = "{{colors.on_surface.default.hex}}"
selection-background = "{{colors.secondary_fixed_dim.default.hex}}"
selection-foreground = "{{colors.on_secondary.default.hex}}"
url_color = "{{colors.primary.default.hex}}"
