command_timeout = 10000

format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$package\
$character
"""

# ─────────────────────────────
# CMD DURATION
# ─────────────────────────────
[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "{{colors.outline.default.hex}}"

# ─────────────────────────────
# DIRECTORY
# ─────────────────────────────
[directory]
format = "[$path]($style) "
style = "bold {{colors.primary.default.hex}}"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "󰎈 "
".config" = " "

# ─────────────────────────────
# GIT BRANCH
# ─────────────────────────────
[git_branch]
symbol = " "
style = "bold {{colors.tertiary.default.hex}}"
format = "[$symbol$branch]($style) "

# ─────────────────────────────
# GIT STATUS
# ─────────────────────────────
[git_status]
use_git_executable = true
ignore_submodules = false
format = "([$all_status$ahead_behind]($style)) "
style = "bold {{colors.on_surface.default.hex}}"

ahead = "[⇡${count}](bold {{colors.primary.default.hex}}) "
modified = "[!${count}](bold {{colors.tertiary.default.hex}}) "
untracked = "[?${count}](bold {{colors.secondary.default.hex}}) "
renamed = "[»${count}](bold {{colors.secondary_fixed.default.hex}}) "
deleted = "[✘${count}](bold {{colors.error.default.hex}}) "

# ─────────────────────────────
# LANGUAGES
# ─────────────────────────────
[python]
symbol = "🐍 "
style = "bold {{colors.tertiary.default.hex}}"

[nodejs]
symbol = " "
style = "bold {{colors.secondary.default.hex}}"

[rust]
symbol = "🦀 "
style = "bold {{colors.error.default.hex}}"

[golang]
symbol = " "
style = "bold {{colors.primary.default.hex}}"

# ─────────────────────────────
# PACKAGE
# ─────────────────────────────
[package]
symbol = "📦 "
style = "bold {{colors.secondary.default.hex}}"

# ─────────────────────────────
# USERNAME
# ─────────────────────────────
[username]
format = "[$user]($style) "
style_user = "bold {{colors.on_surface_variant.default.hex}}"
show_always = true

# ─────────────────────────────
# CHARACTER
# ─────────────────────────────
[character]
success_symbol = "[❯](bold {{colors.primary.default.hex}})"
error_symbol = "[✗](bold {{colors.error.default.hex}})"
vimcmd_symbol = "[](bold {{colors.tertiary.default.hex}})"
