command_timeout = 10000

format = """
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$package\
$character
"""

# ─────────────────────────────
# CMD DURATION
# ─────────────────────────────
[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "#8e9099"

# ─────────────────────────────
# DIRECTORY
# ─────────────────────────────
[directory]
format = "[$path]($style) "
style = "bold #abc7ff"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "󰎈 "
".config" = " "

# ─────────────────────────────
# GIT BRANCH
# ─────────────────────────────
[git_branch]
symbol = " "
style = "bold #ddbce0"
format = "[$symbol$branch]($style) "

# ─────────────────────────────
# GIT STATUS
# ─────────────────────────────
[git_status]
use_git_executable = true
ignore_submodules = false
format = "([$all_status$ahead_behind]($style)) "
style = "bold #e2e2e9"

ahead = "[⇡${count}](bold #abc7ff) "
modified = "[!${count}](bold #ddbce0) "
untracked = "[?${count}](bold #bec6dc) "
renamed = "[»${count}](bold #dae2f9) "
deleted = "[✘${count}](bold #ffb4ab) "

# ─────────────────────────────
# LANGUAGES
# ─────────────────────────────
[python]
symbol = "🐍 "
style = "bold #ddbce0"

[nodejs]
symbol = " "
style = "bold #bec6dc"

[rust]
symbol = "🦀 "
style = "bold #ffb4ab"

[golang]
symbol = " "
style = "bold #abc7ff"

# ─────────────────────────────
# PACKAGE
# ─────────────────────────────
[package]
symbol = "📦 "
style = "bold #bec6dc"

# ─────────────────────────────
# USERNAME
# ─────────────────────────────
[username]
format = "[$user]($style) "
style_user = "bold #abc7ff"
show_always = true

# ─────────────────────────────
# CHARACTER
# ─────────────────────────────
[character]
success_symbol = "[❯](bold #abc7ff)"
error_symbol = "[✗](bold #ffb4ab)"
vimcmd_symbol = "[](bold #ddbce0)"
