[Icon Theme]
Name=Material-Tela
Inherits=Adwaita,hicolor
Comment=Tela folders + Monochrome accent apps

DisplayDepth=32
FollowsColorScheme=true
Example=x-directory-normal

KDE-Extensions=.svg

Directories=actions/scalable,apps/16,apps/scalable,apps/symbolic,categories/scalable,devices/scalable,emblems/scalable,places/scalable,places/symbolic,mimetypes/scalable,mimetypes/scalable-outlined,status/scalable,status/symbolic,preferences/scalable,preferences/symbolic

[actions/scalable]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[apps/16]
Size=128
Context=Applications
Type=Scalable
MinSize=8
MaxSize=24

[apps/scalable]
Size=128
Context=Applications
Type=Scalable
MinSize=25
MaxSize=512

[apps/symbolic]
Context=Applications
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[categories/scalable]
Context=Categories
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[devices/scalable]
Size=128
Context=Devices
Type=Scalable
MinSize=8
MaxSize=128

[emblems/scalable]
Size=128
Context=Actions
Type=Scalable
MinSize=16
MaxSize=128

[places/scalable]
Context=Places
Size=64
MinSize=33
MaxSize=512
Type=Scalable

[places/symbolic]
Context=Places
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[mimetypes/scalable]
Size=512
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[mimetypes/scalable-outlined]
Size=512
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[status/scalable]
Context=Status
Size=64
MinSize=8
MaxSize=512
Type=Scalable

[status/symbolic]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[preferences/scalable]
Context=Applications
Size=64
MinSize=8
MaxSize=512
Type=Scalable

[preferences/symbolic]
Context=Applications
Size=16
MinSize=8
MaxSize=512
Type=Scalable
