[color]
background = 'default'
foreground = '#7AA2F7'  # primary

; gradient = 0
gradient = 1
gradient_color_1 = '#33467C'  # primary_container
gradient_color_2 = '#7AA2F7'  # primary
gradient_color_3 = '#7AA2F7'  # on_primary_container (closest bright accent)

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#33467C'  # primary_container
horizontal_gradient_color_2 = '#7AA2F7'  # primary
horizontal_gradient_color_3 = '#7AA2F7'  # on_primary_container
horizontal_gradient_color_4 = '#7AA2F7'  # primary
horizontal_gradient_color_5 = '#33467C'  # primary_container
