# ==========================
# Tokyo Night - Kitty Theme
# ==========================

# Cursor
cursor             #A9B1D6
cursor_text_color  #1A1B26

# Foreground / Background
foreground            #A9B1D6
background            #1A1B26
selection_foreground  #9ECE6A
selection_background  #3F503E
url_color             #7AA2F7

# Black
color0   #1A1B26
color8   #24283B

# Red
color1   #F7768E
color9   #F7768E

# Green
color2   #9ECE6A
color10  #9ECE6A

# Yellow
color3   #E0AF68
color11  #E0AF68

# Blue
color4   #7AA2F7
color12  #7AA2F7

# Magenta
color5   #BB9AF7
color13  #BB9AF7

# Cyan
color6   #2AC3DE
color14  #2AC3DE

# White / Light shades
color7   #C0CAF5
color15  #A8EDFF
