command_timeout = 10000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$package\
$character
"""

[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "bold #414868"  # surface_variant

[directory]
style = "bold #3f503e"  # secondary_container

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "󰎈 "
".config" = " "

[git_branch]
symbol = " "
style = "bold #7aa2f7"  # primary

[git_status]
use_git_executable = true
ignore_submodules = false
format = "$ahead$modified$untracked$renamed$deleted"
style = "bold #f7768e"  # error
ahead = "⇡:${count} "
renamed = "»:${count} "
deleted = "✘:${count} "
modified = "!:${count} "
untracked = "?:${count} "

[git_metrics]
disabled = true

[python]
symbol = '🐍'
style = "bold #bb9af7"  # tertiary_fixed_dim

[nodejs]
symbol = ""
style = "bold #9ece6a"  # secondary_fixed_dim

[rust]
symbol = "🦀"
style = "bold #f7768e"  # error

[golang]
symbol = ""
style = "bold #7aa2f7"  # primary

[package]
symbol = "📦"
style = "bold #3f503e"  # secondary_container

[username]
format = "[$user]($style) "
style_user = "bold #7aa2f7"  # primary
show_always = true

[hostname]
format = "[@$hostname]($style)"
style = "bold #565f89"  # outline
ssh_only = true

[time]
disabled = false
format = "🕒 %H:%M"
style = "bold #a9b1d6"  # on_surface_variant

[character]
success_symbol = "[❯](bold #33467c)"  # primary_container
error_symbol = "[✗](bold #f7768e)"  # error
vimcmd_symbol = "[](bold #bb9af7)"  # tertiary_fixed_dim
