# : Manager [[[

[manager]
cwd = { fg = "#c0caf5" }

# Tab
tab_active = { fg = "#1e2a47", bg = "#7aa2f7", bold = true }
tab_inactive = { fg = "#33467c", bg = "#161926" }
tab_width = 1

# Find
find_keyword = { fg = "#f7768e", bold = true, italic = true, underline = true }
find_position = { fg = "#f7768e", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c0caf5", bg = "#c0caf5" }
marker_cut = { fg = "#c0caf5", bg = "#c0caf5" }
marker_marked = { fg = "#f7768e", bg = "#f7768e" }
marker_selected = { fg = "#bb9af7", bg = "#bb9af7" }

# Count
count_copied = { fg = "#2a2b3f", bg = "#c0caf5" }
count_cut = { fg = "#2a2b3f", bg = "#c0caf5" }
count_selected = { fg = "#1e2a47", bg = "#bb9af7" }

# Border
border_symbol = "│"
border_style  = { fg = "#7aa2f7" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#1e2a47", fg = "#F4A261" }

[mode]
normal_main = { bg = "#7aa2f7", fg = "#1e2a47", bold = true }
normal_alt  = { bg = "#414868", fg = "#a9b1d6" }

select_main = { bg = "#9ece6a", fg = "#3f503e", bold = true }
select_alt  = { bg = "#414868", fg = "#a9b1d6" }

unset_main = { bg = "#bb9af7", fg = "#6c5dd3", bold = true }
unset_alt  = { bg = "#414868", fg = "#a9b1d6" }

progress_label = { bold = true }
progress_normal = { fg = "#7aa2f7", bg = "#24283b" }
progress_error = { fg = "#f7768e", bg = "#24283b" }

permissions_t = { fg = "#6c5dd3" }
permissions_w = { fg = "#bb9af7" }
permissions_x = { fg = "#f7768e" }
permissions_r = { fg = "#c0caf5" }
permissions_s = { fg = "#33467c" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#7aa2f7" }
active = { fg = "#bb9af7", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#7aa2f7" }
value = { fg = "#c0caf5" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#7aa2f7", bg = "#1e2a47" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7aa2f7" }
title = {}
hovered = { fg = "#c0caf5", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#24283b" }
cand = { fg = "#7aa2f7" }
rest = { fg = "#1e2a47" }
desc = { fg = "#c0caf5" }
separator = " ▶ "
separator_style = { fg = "#c0caf5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#c0caf5" }
run = { fg = "#c0caf5" }
footer = { fg = "#9ece6a", bg = "#3f503e" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bb9af7" }
title_warn = { fg = "#7aa2f7" }
title_error = { fg = "#f7768e" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#813747" },
    { name = "*", is = "exec", fg = "#f5c2c6" },

    # Fallback
    { name = "*", fg = "#c0caf5" },
    { name = "*/", fg = "#7aa2f7" },
]

# : ]]]
