# 🖥️ Video Output and Hardware Decoding
vo=gpu
hwdec=auto
gpu-context=wayland

# 🔲 Window Behavior
autofit-larger=100%x100%
border=no
save-position-on-quit=yes
deband=no
#osd-bar=no
video-sync=display-resample

script-opts-append=uosc=yes

# OSD
osd-color="#dbffff"
osd-border-color="#0b1d24"
osd-font="JetBrains Mono"
osd-font-size=55
osd-bold=yes
osd-shadow-offset=1.5

# Subtitle Styling
sub-color="#dbffff"
sub-border-color="#1a110f"
sub-shadow-color="#000000"
sub-font="JetBrains Mono"
sub-font-size=30
sub-border-size=2.5
sub-shadow-offset=2

# Optional OSD position
osd-align-x=center
osd-align-y=top
osd-margin-y=20


sub-font-size=40

no-keepaspect-window
