# 🖥️ Video Output and Hardware Decoding
vo = gpu-next
hwdec = auto-safe
gpu-context = wayland

# 🔲 Window Behavior
autofit-larger = 100%x100%
border = no
save-position-on-quit = yes
deband = no
osd-bar = no
video-sync = display-resample

script-opts-append = uosc = yes

# 🎨 Matugen Theming & Typography
osd-font = "Cantarell"
sub-font = "Cantarell"

# Works perfectly with the native '#' prefix from Matugen
osd-color = "#b7cea0"
sub-color = "#b7cea0"
sub-border-color = "#131411"

sub-border-size = 2
sub-font-size = 40

volume-max = 150
no-keepaspect-window
