# Matugen template for btop

theme[main_bg]=""
theme[main_fg]="#ebdbb2"
theme[title]="#83a598"
theme[hi_fg]="#d5c4a1"
theme[selected_bg]="#83a598"
theme[selected_fg]="#282828"
theme[inactive_fg]="#d5c4a1"
theme[proc_misc]="#d3869b"
theme[cpu_box]="#928374"
theme[mem_box]="#928374"
theme[net_box]="#928374"
theme[proc_box]="#928374"
theme[div_line]="#665c54"

theme[temp_start]="#d5c4a1"
theme[temp_mid]="#83a598"
theme[temp_end]="#fb4934"

theme[cpu_start]="#d5c4a1"
theme[cpu_mid]="#83a598"
theme[cpu_end]="#fb4934"

theme[free_start]="#d5c4a1"
theme[free_mid]=""
theme[free_end]="#3c3836"

theme[cached_start]="#d3869b"
theme[cached_mid]=""
theme[cached_end]="#3c3836"

theme[available_start]="#83a598"
theme[available_mid]=""
theme[available_end]="#3c3836"

theme[used_start]="#fb4934"
theme[used_mid]=""
theme[used_end]="#cc241d"

theme[download_start]="#d5c4a1"
theme[download_mid]="#83a598"
theme[download_end]="#d3869b"

theme[upload_start]="#d5c4a1"
theme[upload_mid]="#83a598"
theme[upload_end]="#d3869b"
