cursor #ebdbb2
cursor_text_color #d5c4a1

foreground            #ebdbb2
background            #1d2021
selection_foreground  #282828
selection_background  #bdae93
url_color             #83a598

# black
color8   #262626
color0   #4c4c4c

# red
color1   #fb4934
color9   #cc241d

# green
color2   #8ec07c
color10  #689d6a

# yellow
color3   #fabd2f
color11  #d79921

# blue
color4   #83a598
color12  #a39ec4

# magenta
color5   #d3869b
color13  #83a598

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15  #ebdbb2
color7   #f0f0f0
