command_timeout = 10000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$package\
$character
"""

[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "bold #d5c4a1"

[directory]
style = "bold #3c3836"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "󰎈 "
".config" = " "

[git_branch]
symbol = " "
style = "bold #83a598"

[git_status]
use_git_executable = true
ignore_submodules = false
format = "$ahead$modified$untracked$renamed$deleted"
style = "bold #fb4934"
ahead = "⇡:${count} "
renamed = "»:${count} "
deleted = "✘:${count} "
modified = "!:${count} "
untracked = "?:${count} "

[git_metrics]
disabled = true

[python]
symbol = '🐍'
style = "bold #665c54"

[nodejs]
symbol = ""
style = "bold #b2c0c0"

[rust]
symbol = "🦀"
style = "bold #fb4934"

[golang]
symbol = ""
style = "bold #83a598"

[package]
symbol = "📦"
style = "bold #3c3836"

[username]
format = "[$user]($style) "
style_user = "bold #83a598"
show_always = true

[hostname]
format = "[@$hostname]($style)"
style = "bold #928374"
ssh_only = true

[time]
disabled = false
format = "🕒 %H:%M"
style = "bold #d5c4a1"

[character]
success_symbol = "[❯](bold #3c3836)"
error_symbol = "[✗](bold #fb4934)"
vimcmd_symbol = "[](bold #665c54)"
