# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f3ded7"

# Title color for boxes
theme[title]="#ffb695"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#fcb798"

# Background color of selected item in processes box
theme[selected_bg]="#ffb695"

# Foreground color of selected item in processes box
theme[selected_fg]="#571e00"

# Color of inactive/disabled text
theme[inactive_fg]="#ddc1b5"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#6bd3fd"

# Cpu box outline color
theme[cpu_box]="#a58b81"

# Memory/disks box outline color
theme[mem_box]="#a58b81"

# Net up/down box outline color
theme[net_box]="#a58b81"

# Processes box outline color
theme[proc_box]="#a58b81"

# Box divider line and small boxes line color
theme[div_line]="#57423a"

# Temperature graph colors
theme[temp_start]="#fcb798"
theme[temp_mid]="#ffb695"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#fcb798"
theme[cpu_mid]="#ffb695"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#fcb798"
theme[free_mid]=""
theme[free_end]="#6a3a24"

# Mem/Disk cached meter
theme[cached_start]="#6bd3fd"
theme[cached_mid]=""
theme[cached_end]="#249cc4"

# Mem/Disk available meter
theme[available_start]="#ffb695"
theme[available_mid]=""
theme[available_end]="#e17138"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#fcb798"
theme[download_mid]="#ffb695"
theme[download_end]="#6bd3fd"

# Upload graph colors
theme[upload_start]="#fcb798"
theme[upload_mid]="#ffb695"
theme[upload_end]="#6bd3fd"
