# --- Main Colors ---
background            #111318
foreground            #e2e2e9
cursor                #e2e2e9
cursor_text_color     #111318

selection_background  #3e4759
selection_foreground  #dae2f9

url_color             #ddbce0

# --- ANSI Colors ---
color0                #111318
color1                #ffb4ab
color2                #fad8fc
color3                #dae2f9
color4                #abc7ff
color5                #ddbce0
color6                #bec6dc
color7                #e2e2e9

color8                #44474e
color9                #93000a
color10               #573e5b
color11               #3e4759
color12               #294677
color13               #3e4759
color14               #573e5b
color15               #c4c6d0

# --- Starship Prompt Bubbles ---
color255              #294677
color254              #abc7ff
color253              #3e4759
color252              #bec6dc
color251              #573e5b
color250              #ddbce0
color249              #93000a
color248              #ffb4ab

color232              #d7e2ff
color233              #0d2f5f
color234              #dae2f9
color235              #283041
color236              #fad8fc
color237              #3f2844
color238              #ffdad6
color239              #690005
color240              #d7e2ff
color241			  #33353a

# Matched with unthemed light/dark
color243              #abc7ff
color244              #ffb4ab
color245              #44474e

# --- UI Elements ---
active_tab_foreground   #0d2f5f
active_tab_background   #abc7ff
inactive_tab_foreground #e2e2e9
inactive_tab_background #282a2f

active_border_color     #abc7ff
inactive_border_color   #8e9099

# --- Marks ---
mark1_foreground        #001b3f
mark1_background        #d7e2ff
mark2_foreground        #131c2c
mark2_background        #dae2f9
mark3_foreground        #29132e
mark3_background        #fad8fc
