cursor            #ffb695
cursor_text_color #571e00

foreground            #f3ded7
background            #1b110d
selection_foreground  #4f2510
selection_background  #fcb798
url_color             #fcb798

#: black 000000 767676
color0  #1b110d
color8  #3e322d
#: red cc0403 f2201f
color1  #9f612c
color9  #deaf86
#: green 19cb00 23fd00
color2  #fcb798
color10 #ffdbcc
#: yellow cecb00 fffd00
color3  #6bd3fd
color11 #bde9ff
#: blue 0d73cc 1a8fff
color12  #571e00
color4 #ffb695
#: magenta cb1ed1 fd28ff
color5  #6a3a24
color13 #fcb798
#: cyan 0dcdcd 14ffff
color6  #004d64
color14 #6bd3fd
#: white dddddd ffffff
color7  #ddc1b5
color15 #f3ded7

mark1_foreground #351000
mark1_background #ffdbcc
mark2_foreground #341101
mark2_background #ffdbcc
mark3_foreground #001f2a
mark3_background #bde9ff

active_tab_foreground #571e00
active_tab_background #ffb695
inactive_tab_foreground #000000
inactive_tab_background #e17138

active_border_color #ffb695
inactive_border_color #571e00
# bell_border_color #ff5a00
