# Matugen template for btop with Rosé Pine colors

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0def4"

# Title color for boxes
theme[title]="#ebbcba"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ebbcba"

# Background color of selected item in processes box
theme[selected_bg]="#ebbcba"

# Foreground color of selected item in processes box
theme[selected_fg]="#e0def4"

# Color of inactive/disabled text
theme[inactive_fg]="#c4a7e7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c4a7e7"

# Cpu box outline color
theme[cpu_box]="#6e6a86"

# Memory/disks box outline color
theme[mem_box]="#6e6a86"

# Net up/down box outline color
theme[net_box]="#6e6a86"

# Processes box outline color
theme[proc_box]="#6e6a86"

# Box divider line and small boxes line color
theme[div_line]="#403d52"

# Temperature graph colors
theme[temp_start]="#ebbcba"
theme[temp_mid]="#ebbcba"
theme[temp_end]="#eb6f92"

# CPU graph colors
theme[cpu_start]="#ebbcba"
theme[cpu_mid]="#ebbcba"
theme[cpu_end]="#eb6f92"

# Mem/Disk free meter
theme[free_start]="#ebbcba"
theme[free_mid]=""
theme[free_end]="#b4637a"

# Mem/Disk cached meter
theme[cached_start]="#c4a7e7"
theme[cached_mid]=""
theme[cached_end]="#6e6a86"

# Mem/Disk available meter
theme[available_start]="#ebbcba"
theme[available_mid]=""
theme[available_end]="#b4637a"

# Mem/Disk used meter
theme[used_start]="#eb6f92"
theme[used_mid]=""
theme[used_end]="#b4637a"

# Download graph colors
theme[download_start]="#ebbcba"
theme[download_mid]="#ebbcba"
theme[download_end]="#c4a7e7"

# Upload graph colors
theme[upload_start]="#ebbcba"
theme[upload_mid]="#ebbcba"
theme[upload_end]="#c4a7e7"

