cursor                #e0def4
cursor_text_color     #c4a7e7

foreground            #e0def4
background            #1f1d2e
selection_foreground  #e0def4
selection_background  #b2cbd2
url_color             #ebbcba

# black
color8   #26233a
color0   #1f1d2e

# red
color1   #eb6f92
color9   #b4637a

# green
color2   #84d2e5
color10  #a8edff

# yellow
color3   #c4a7e7
color11  #6e6a86

# blue
color4   #ebbcba
color12  #a39ec4

# magenta
color5   #c4a7e7
color13  #ebbcba

# cyan
color6   #84d2e5
color14  #9ec3c4

# white
color15  #e0def4
color7   #f0f0f0

