command_timeout = 10000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$package\
$character
"""

[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "bold #7f849c"  # surface_variant.default

[directory]
style = "bold #f2cdcd"  # secondary_container.default

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "󰎈 "
".config" = " "

[git_branch]
symbol = " "
style = "bold #ebbcba"  # primary.default

[git_status]
use_git_executable = true
ignore_submodules = false
format = "$ahead$modified$untracked$renamed$deleted"
style = "bold #f38ba8"  # error
ahead = "⇡:${count} "
renamed = "»:${count} "
deleted = "✘:${count} "
modified = "!:${count} "
untracked = "?:${count} "

[git_metrics]
disabled = true

[python]
symbol = '🐍'
style = "bold #9ccfd8"  # tertiary_fixed_dim.default

[nodejs]
symbol = ""
style = "bold #c3bac6"  # secondary_fixed_dim.default

[rust]
symbol = "🦀"
style = "bold #f38ba8"  # error

[golang]
symbol = ""
style = "bold #ebbcba"  # primary.default

[package]
symbol = "📦"
style = "bold #f2cdcd"  # secondary_container.default

[username]
format = "[$user]($style) "
style_user = "bold #ebbcba"  # primary.default
show_always = true

[hostname]
format = "[@$hostname]($style)"
style = "bold #6c7086"  # outline.default
ssh_only = true

[time]
disabled = false
format = "🕒 %H:%M"
style = "bold #7f849c"  # on_surface_variant.default

[character]
success_symbol = "[❯](bold #f2cdcd)"   # primary_container.default
error_symbol = "[✗](bold #f38ba8)"      # error
vimcmd_symbol = "[](bold #9ccfd8)"     # tertiary_fixed_dim.default

