format = """
[╭](fg:current_line)\
$directory\
$git_branch\
$git_status\
$rust\
$python\
$cmd_duration\
$line_break\
$character\
"""

palette = 'colors'

[palettes.colors]
color0 = '%%color0%%'
color1 = '%%color1%%'
color2 = '%%color2%%'
color3 = '%%color3%%'
color4 = '%%color4%%'
color5 = '%%color5%%'
color6 = '%%color6%%'
color7 = '%%color7%%'
color8 = '%%color8%%'
color9 = '%%color9%%'
color10 = '%%color10%%'
color11 = '%%color11%%'
color12 = '%%color12%%'
color13 = '%%color13%%'
color14 = '%%color14%%'
color15 = '%%color15%%'
 
[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = "[🞈](color9 bold)"
error_symbol = "[🞈](@{error})"
vicmd_symbol = "[🞈](#f9e2af)"

[directory]
format = "(fg:current_line)[](fg:color1 bg:color4)[󰉋](bg:color1 fg:color2)[ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[ ](fg:color4)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "󰎈 "
".config" = " "

[git_branch]
format = "(fg:current_line)[](fg:color8 bg:color4)[$symbol](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $branch](fg:color3 bg:color4)"
symbol = ''

[git_status]
format = '[$all_status](fg:green bg:color4)[ ](fg:color4)'
conflicted = ' ='
up_to_date = ''
untracked = ' ?${count}'
stashed = ' $'
modified = ' !${count}'
staged = ' +'
renamed = ' »'
deleted = ' ✘'
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'

[cmd_duration]
min_time = 5
show_milliseconds = true

[python]
format = "[](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[](fg:color4) "
symbol = '🐍'
pyenv_prefix = 'venv'
