[general]
color = "#85a79a"
interval = 200
blink = false
bold = false

[position]
horizontal = "center"
vertical = "center"

[date]
fmt = "%A, %B %d, %Y"
use_12h = true
utc = false
hide_seconds = true
