cursor            #b7cea0
cursor_text_color #243515

foreground            #e4e2dd
background            #131411
selection_foreground  #2b3323
selection_background  #c1cab4
url_color             #c1cab4

#: black 000000 767676
color0  #131411
color8  #343531
#: red cc0403 f2201f
color1  #93000a
color9  #ffb4ab
#: green 19cb00 23fd00
color2  #c1cab4
color10 #dde6cf
#: yellow cecb00 fffd00
color3  #eab8d4
color11 #ffd8ec
#: blue 0d73cc 1a8fff
color12  #243515
color4 #b7cea0
#: magenta cb1ed1 fd28ff
color5  #414939
color13 #c1cab4
#: cyan 0dcdcd 14ffff
color6  #603b52
color14 #eab8d4
#: white dddddd ffffff
color7  #c5c8bc
color15 #e4e2dd

mark1_foreground #0f2003
mark1_background #d3eabb
mark2_foreground #161e10
mark2_background #dde6cf
mark3_foreground #2f1125
mark3_background #ffd8ec

active_tab_foreground #243515
active_tab_background #b7cea0
inactive_tab_foreground #ffffff
inactive_tab_background #566a44

active_border_color #b7cea0
inactive_border_color #243515
# bell_border_color #ff5a00
