# --- Main Colors ---
background            #141319
foreground            #e5e1ea
cursor                #e5e1ea
cursor_text_color     #141319

selection_background  #474268
selection_foreground  #e3dcff

url_color             #f5bd5e

# --- ANSI Colors ---
color0                #141319
color1                #ffb4ab
color2                #ffdeac
color3                #e5deff
color4                #c9bfff
color5                #f5bd5e
color6                #c9c1ee
color7                #e5e1ea

color8                #484552
color9                #93000a
color10               #8b6000
color11               #474268
color12               #695abc
color13               #474268
color14               #604100
color15               #c9c4d4

# --- Starship Prompt Bubbles ---
color255              #695abc
color254              #c9bfff
color253              #474268
color252              #c9c1ee
color251              #8b6000
color250              #f5bd5e
color249              #93000a
color248              #ffb4ab

color232              #ffffff
color233              #301c80
color234              #e3dcff
color235              #312c50
color236              #ffffff
color237              #432c00
color238              #ffdad6
color239              #690005
color240              #ffffff
color241			  #35343b

# Matched with unthemed light/dark
color243              #c9bfff
color244              #ffb4ab
color245              #484552

# --- UI Elements ---
active_tab_foreground   #301c80
active_tab_background   #c9bfff
inactive_tab_foreground #e5e1ea
inactive_tab_background #2b2930

active_border_color     #c9bfff
inactive_border_color   #938f9d

# --- Marks ---
mark1_foreground        #1a0063
mark1_background        #e5deff
mark2_foreground        #1c163a
mark2_background        #e5deff
mark3_foreground        #281900
mark3_background        #ffdeac
